# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

knn_cross <- function(data, query, k, distance = "euclidean") {
    .Call('_knn_covertree_knn_cross', PACKAGE = 'knn.covertree', data, query, k, distance)
}

knn_asym <- function(data, k, distance = "euclidean") {
    .Call('_knn_covertree_knn_asym', PACKAGE = 'knn.covertree', data, k, distance)
}

rank_mat <- function(x) {
    .Call('_knn_covertree_rank_mat', PACKAGE = 'knn.covertree', x)
}

